---

- name: ssl key/crt
  shell: "mkdir /etc/logstash/ssl; openssl req -subj '/CN=localhost/' -x509 -batch -nodes -newkey rsa:2048 -keyout /etc/logstash/ssl/logstash-forwarder.key -out /etc/logstash/ssl/logstash-forwarder.crt"
  args:
    creates: /etc/logstash/ssl

- name: logstash-forwarder config
  copy:
    src=logstash-forwarder.conf
    dest=/etc/logstash-forwarder.conf
  notify: restart logstash-forwarder

- name: logstash logstash-forwarder input config
  synchronize:
    src=roles/logstash_forwarder/files/conf.d/
    dest=/etc/logstash/conf.d/
    recursive=yes
  notify: restart logstash

- name: apt-key
  apt_key:
    url="http://packages.elasticsearch.org/GPG-KEY-elasticsearch"
    state=present

- name: repository
  apt_repository:
    repo="deb http://packages.elasticsearch.org/logstashforwarder/debian stable main"
    state=present

- name: package
  apt:
    name=logstash-forwarder
    state=present
  notify: restart logstash-forwarder

- name: service
  service:
    name=logstash-forwarder
    enabled=yes
    state=started
